### ISSUE TITLE
Issues with 2023.2.0b1

### ISSUE THREAD

**Issue by Thrasher2020** [Limych/ha-iaquk#104]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:601
Integration: Sensor (documentation, issues)
First occurred: 10:57:36 (14 occurrences)
Last logged: 11:00:36

Sensor sensor.living_room_iaq_level has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: Excellent (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

-->

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Spiffo** [comment]
Same here
