### ISSUE TITLE
Is it possible to use VOC index instead of TVOC?

### ISSUE THREAD

**Issue by RASTRILL0** [Limych/ha-iaquk#115]
**Is your feature request related to a problem? Please describe.**

The SGP40 and SGP41 gas sensors report VOC as an index. The index is unit-less and bounded between 0–500 steps from the best to the worst air quality level. These sensors are pretty good at detecting VOC in realistic lab tests (see Al-Okby et al, 2022: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8876806/ ). Table 1 in the linked paper offers an approximation of TVOC levels compared to the VOC index values reported by the SGP4X sensors. 

**Describe the solution you'd like**
Suggest adding a new unit to tvoc in ha-iaquk called 'index' that converts index values and corresponding PPM values to determine the TVOC placement on the IAQUK rating index.

**Describe alternatives you've considered**
I could try to manually add a template sensor to HA configuration.yaml to create a surrogate TVOC from VOC Index but I think with the popularity of these sensors, it might make more sense to solve the issue in the project itself.

**Additional context**

![Screen Shot 2023-03-10 at 6 55 22 PM](https://user-images.githubusercontent.com/63689845/224455291-ec87e540-2379-4e6d-89f0-eb6ff464a12d.png)

**Comment by Limych** [comment]
@RASTRILL0 
Test it, please.

**Comment by RASTRILL0** [comment]
Sorry for the delay. Got a chance to try it out today and everything seems to be working great. Thanks so much!
