### ISSUE TITLE
Sources set = 3, sources used = 0

### ISSUE THREAD

**Issue by jjanderson** [Limych/ha-iaquk#119]
Hi,

With the last update, I am no longer getting any values coming through with 

Sources set = 3

Sources used = 0

I am using the tether sensors and using a rest integration. Everything was working fine until the update

![image](https://github.com/Limych/ha-iaquk/assets/1214287/ae18b810-761e-4801-90ce-992af5809a2a)

My IAQUK config example is:

tether02:
  name: "tether 02"
  sources:
    temperature: sensor.tether02_temp
    humidity: sensor.tether02_humidity
    co2: sensor.tether02_co2
  sensors:
    - iaq_level
    - iaq_index

The sensors are configured as rest sensors as follows:

  - scan_interval: 300
    resource: https://api.tether.co.nz/v2/device/XXXXXXXXXXXXXXXXXXXXXX/latest
    headers:
      Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    sensor:
      - name: tether02_temp
        value_template: "{{ value_json.sample.temperature }}"
        device_class: temperature
        unit_of_measurement: "°C"
        unique_id: tether02_temp

      - name: tether02_co2
        value_template: "{{ value_json.sample.co2 }}"
        device_class: carbon_dioxide
        unit_of_measurement: "ppm"
        unique_id: tether02_co2

      - name: tether02_batteryraw
        json_attributes_path: "$.response.system"
        value_template: "{{ value_json.sample.batteryRaw }}"
        unique_id: tether02_batteryraw

      - name: tether02_battery
        unique_id: tether02_battery
        value_template: "{{ value_json.sample.battery }}"
        device_class: battery
        unit_of_measurement: "%"

      - name: tether02_light
        unique_id: tether02_light
        value_template: "{{ value_json.sample.light }}"
        device_class: illuminance
        unit_of_measurement: "lx"

      - name: tether02_lightraw
        unique_id: tether02_lightraw
        value_template: "{{ value_json.sample.lightRaw }}"

      - name: tether02_sound
        unique_id: tether02_sound
        value_template: "{{ value_json.sample.sound }}"
        device_class: sound_pressure
        unit_of_measurement: "dB"

      - name: tether02_humidity
        unique_id: tether02_humidity
        value_template: "{{ value_json.sample.humidity }}"
        device_class: humidity
        unit_of_measurement: "%"

      - name: tether02_pressure
        unique_id: tether02_pressure
        value_template: "{{ value_json.sample.pressure }}"
        device_class: pressure
        unit_of_measurement: "kPa"

      - name: tether02_dewPoint
        unique_id: tether02_dewPoint
        value_template: "{{ value_json.sample.dewPoint }}"

Any help would be greatly appreciated

Thanks

**Comment by jjanderson** [comment]
I see index is actually working but it is the Level that is not, It would appear that this issue has already been reported.

It would however be good to get an update on ETA for a fix.

Please do let me know if you need any help with testing, otherwise, thanks very much for all your hard work in bringing this to us here on Jersey!

**Comment by smarrk** [comment]
Please take a look at your system log. You probably see

> ValueError: Sensor sensor.iaq_level_office has device class None, state class measurement unit None and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: Good (<class 'str'>)

If so, this error is taken care of in #116 (currently not merged)
