### ISSUE TITLE
The method for providing platform translations has changed in Home Assistant Core

### ISSUE THREAD

**Issue by emontnemery** [Limych/ha-iaquk#143]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The method for providing platform translations has changed in Home Assistant Core, and this integration needs to be updated.

### Describe the solution you'd like

Update the integrations

### Describe alternatives you've considered

Drop translations

### Additional context

https://developers.home-assistant.io/blog/2024/03/05/platform_entity_translations_deprecation

**Comment by Limych** [comment]
Thank you for your attention to the project. The change in how localizations are stored that you refer to only applies to Home Assistant Core components. Custom components store localizations the old fashioned way.

See more: https://developers.home-assistant.io/docs/internationalization/custom_integration
